from collections import OrderedDict

var_titles = OrderedDict([
    ("t", r"t [s]"),
    ("x", r"x [m]"),
    ("y", r"y [m]"),
    ("z", r"z [m]"),
    ("vx", r"v_x [m/s]"),
    ("vy", r"v_y [m/s]"),
    ("vz", r"v_z [m/s]"),
    ("yaw", r"yaw [deg]"),
    ("pitch", r"pitch [deg]"),
    ("roll", r"roll [deg]"),
    ("wx", r"w_x [deg/s]"),
    ("wy", r"w_y [deg/s]"),
    ("wz", r"w_z [deg/s]"),
    ("servo1", r"servo1 [deg]"),
    ("servo2", r"servo2 [deg]"),
    ("bottom", r"P_B [\%]"),
    ("top", r"P_T [\%]"),
    ("thrust_scaling", r"thrust scaling"),
    ("torque_scaling", r"torque scaling"),
    ("servo1_offset", r"servo1 offset [deg]"),
    ("servo2_offset", r"servo2 offset [deg]"),
    ("disturbance_force_x", r"F_x [N]"),
    ("disturbance_force_y", r"F_y [N]"),
    ("disturbance_force_z", r"F_z [N]"),
    ("disturbance_torque_x", r"M_x [Nm]"),
    ("disturbance_torque_y", r"M_y [Nm]"),
    ("disturbance_torque_z", r"M_z [Nm]"),
])

var_titles_latex = OrderedDict([
    ("t", r"$\boldsymbol{t}$ [s]"),
    ("x", r"$\boldsymbol{x}$ [m]"),
    ("y", r"$\boldsymbol{y}$ [m]"),
    ("z", r"$\boldsymbol{z}$ [m]"),
    ("vx", r"$\boldsymbol{v_x}$ [m/s]"),
    ("vy", r"$\boldsymbol{v_y}$ [m/s]"),
    ("vz", r"$\boldsymbol{v_z}$ [m/s]"),
    ("yaw", r"$\boldsymbol{\alpha}$ [$\degree$]"),
    ("pitch", r"$\boldsymbol{\beta}$ [$\degree$]"),
    ("roll", r"$\boldsymbol{\gamma}$ [$\degree$]"),
    ("wx", r"$\boldsymbol{\omega_x}$ [$\degree$/s]"),
    ("wy", r"$\boldsymbol{\omega_y}$ [$\degree$/s]"),
    ("wz", r"$\boldsymbol{\omega_z}$ [$\degree$/s]"),
    ("servo1", r"$\boldsymbol{\theta_1}$ [$\degree$]"),
    ("servo2", r"$\boldsymbol{\theta_2}$ [$\degree$]"),
    ("bottom", r"$\boldsymbol{P_B}$ [\%]"),
    ("top", r"$\boldsymbol{P_T}$ [\%]"),
    ("thrust_scaling", r"thrust scaling"),
    ("torque_scaling", r"torque scaling"),
    ("servo1_offset", r"servo1 offset [$\degree$]"),
    ("servo2_offset", r"servo2 offset [$\degree$]"),
    ("disturbance_force_x", r"$\boldsymbol{F_x}$ [N]"),
    ("disturbance_force_y", r"$\boldsymbol{F_y}$ [N]"),
    ("disturbance_force_z", r"$\boldsymbol{F_z}$ [N]"),
    ("disturbance_torque_x", r"$\boldsymbol{M_x}$ [Nm]"),
    ("disturbance_torque_y", r"$\boldsymbol{M_y}$ [Nm]"),
    ("disturbance_torque_z", r"$\boldsymbol{M_z}$ [Nm]"),
])
